### ISSUE TITLE
exports.locals issue

### ISSUE THREAD

**Issue by gencer** [ifmos/typings-for-css-modules-loader#1]
Hi,

Thanks for the updated extension!

I -_like you said in README_- have an `exports.locals` issue. Currently I do not have webpack configuration because I am using Rails' Webpacker.

This is how I applied your extension:

```
environment.loaders.get('moduleSass').use = environment.loaders.get('moduleSass').use.map((u) => {
  if(u.loader == 'css-loader') {
    return { ...u, loader: 'better-typings-for-css-modules-loader?modules&sass' };
  } else {
    return u;
  }
})
```

In this case how can I solve with above declaration for `locals` problem? Can you help me on this?

**Comment by ifmos** [comment]
Hi @gencer, sorry about that I haven't used Rails' Webpacker. You can provide more infomation.
